// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type DPool struct {
	ID                           *string    `json:"id"`
	Address                      *string    `json:"address"`
	MoneyMarket                  *string    `json:"moneyMarket"`
	Stablecoin                   *string    `json:"stablecoin"`
	InterestModel                *string    `json:"interestModel"`
	Users                        []*User    `json:"users"`
	NumUsers                     *int       `json:"numUsers"`
	Deposits                     []*Deposit `json:"deposits"`
	NumDeposits                  *int       `json:"numDeposits"`
	NumActiveDeposits            *string    `json:"numActiveDeposits"`
	TotalActiveDeposit           *string    `json:"totalActiveDeposit"`
	TotalHistoricalDeposit       *string    `json:"totalHistoricalDeposit"`
	TotalInterestPaid            *string    `json:"totalInterestPaid"`
	UnfundedDepositAmount        *string    `json:"unfundedDepositAmount"`
	Funders                      []*Funder  `json:"funders"`
	NumFunders                   *string    `json:"numFunders"`
	Fundings                     []*Funding `json:"fundings"`
	NumFundings                  *string    `json:"numFundings"`
	MinDepositPeriod             *float64   `json:"MinDepositPeriod"`
	MaxDepositPeriod             *float64   `json:"MaxDepositPeriod"`
	MinDepositAmount             *float64   `json:"MinDepositAmount"`
	MaxDepositAmount             *float64   `json:"MaxDepositAmount"`
	MphMintingMultiplier         *float64   `json:"mphMintingMultiplier"`
	MphDepositorRewardMultiplier *float64   `json:"mphDepositorRewardMultiplier"`
	MphFunderRewardMultiplier    *float64   `json:"mphFunderRewardMultiplier"`
	OneYearInterestRate          *float64   `json:"oneYearInterestRate"`
	Surplus                      *string    `json:"surplus"`
	MoneyMarketIncomeIndex       *string    `json:"moneyMarketIncomeIndex"`
	OracleInterestRate           *string    `json:"oracleInterestRate"`
}

type DPoolInput struct {
	ID                           *string         `json:"id"`
	Address                      *string         `json:"address"`
	MoneyMarket                  *string         `json:"moneyMarket"`
	Stablecoin                   *string         `json:"stablecoin"`
	InterestModel                *string         `json:"interestModel"`
	Users                        []*UserInput    `json:"users"`
	NumUsers                     *int            `json:"numUsers"`
	Deposits                     []*DepositInput `json:"deposits"`
	NumDeposits                  *int            `json:"numDeposits"`
	NumActiveDeposits            *string         `json:"numActiveDeposits"`
	TotalActiveDeposit           *string         `json:"totalActiveDeposit"`
	TotalHistoricalDeposit       *string         `json:"totalHistoricalDeposit"`
	TotalInterestPaid            *string         `json:"totalInterestPaid"`
	UnfundedDepositAmount        *string         `json:"unfundedDepositAmount"`
	Funders                      []*FunderInput  `json:"funders"`
	NumFunders                   *string         `json:"numFunders"`
	Fundings                     []*FundingInput `json:"fundings"`
	NumFundings                  *string         `json:"numFundings"`
	MinDepositPeriod             *float64        `json:"MinDepositPeriod"`
	MaxDepositPeriod             *float64        `json:"MaxDepositPeriod"`
	MinDepositAmount             *float64        `json:"MinDepositAmount"`
	MaxDepositAmount             *float64        `json:"MaxDepositAmount"`
	MphMintingMultiplier         *float64        `json:"mphMintingMultiplier"`
	MphDepositorRewardMultiplier *float64        `json:"mphDepositorRewardMultiplier"`
	MphFunderRewardMultiplier    *float64        `json:"mphFunderRewardMultiplier"`
	OneYearInterestRate          *float64        `json:"oneYearInterestRate"`
	Surplus                      *string         `json:"surplus"`
	MoneyMarketIncomeIndex       *string         `json:"moneyMarketIncomeIndex"`
	OracleInterestRate           *string         `json:"oracleInterestRate"`
}

type DPoolList struct {
	ID             *string  `json:"id"`
	Pools          []*DPool `json:"pools"`
	NumPools       *int     `json:"numPools"`
	NumUsers       *int     `json:"numUsers"`
	NumActiveUsers *int     `json:"numActiveUsers"`
	NumFunders     *int     `json:"numFunders"`
}

type DPoolListInput struct {
	ID             *string       `json:"id"`
	Pools          []*DPoolInput `json:"pools"`
	NumPools       *int          `json:"numPools"`
	NumUsers       *int          `json:"numUsers"`
	NumActiveUsers *int          `json:"numActiveUsers"`
	NumFunders     *int          `json:"numFunders"`
}

type Deposit struct {
	ID                            *string `json:"id"`
	NftID                         *string `json:"nftID"`
	User                          *User   `json:"user"`
	Pool                          *DPool  `json:"pool"`
	Amount                        *string `json:"amount"`
	MaturationTimestamp           *string `json:"maturationTimestamp"`
	Active                        *bool   `json:"active"`
	DepositTimestamp              *string `json:"depositTimestamp"`
	InterestEarned                *string `json:"interestEarned"`
	FundingID                     *string `json:"fundingID"`
	MintMPHAmount                 *string `json:"mintMPHAmount"`
	TakeBackMPHAmount             *string `json:"takeBackMPHAmount"`
	InitialMoneyMarketIncomeIndex *string `json:"initialMoneyMarketIncomeIndex"`
}

type DepositInput struct {
	ID                            *string     `json:"id"`
	NftID                         *string     `json:"nftID"`
	User                          *UserInput  `json:"user"`
	Pool                          *DPoolInput `json:"pool"`
	Amount                        *string     `json:"amount"`
	MaturationTimestamp           *string     `json:"maturationTimestamp"`
	Active                        *bool       `json:"active"`
	DepositTimestamp              *string     `json:"depositTimestamp"`
	InterestEarned                *string     `json:"interestEarned"`
	FundingID                     *string     `json:"fundingID"`
	MintMPHAmount                 *string     `json:"mintMPHAmount"`
	TakeBackMPHAmount             *string     `json:"takeBackMPHAmount"`
	InitialMoneyMarketIncomeIndex *string     `json:"initialMoneyMarketIncomeIndex"`
}

type Funder struct {
	ID                  *string                `json:"id"`
	Address             *string                `json:"address"`
	Pools               []*DPool               `json:"pools"`
	NumPools            *string                `json:"numPools"`
	Fundings            []*Funding             `json:"fundings"`
	NumFundings         *string                `json:"numFundings"`
	TotalMPHEarned      *string                `json:"totalMPHEarned"`
	TotalInterestByPool []*FunderTotalInterest `json:"totalInterestByPool"`
}

type FunderInput struct {
	ID                  *string                     `json:"id"`
	Address             *string                     `json:"address"`
	Pools               []*DPoolInput               `json:"pools"`
	NumPools            *string                     `json:"numPools"`
	Fundings            []*FundingInput             `json:"fundings"`
	NumFundings         *string                     `json:"numFundings"`
	TotalMPHEarned      *string                     `json:"totalMPHEarned"`
	TotalInterestByPool []*FunderTotalInterestInput `json:"totalInterestByPool"`
}

type FunderTotalInterest struct {
	ID                               *string `json:"id"`
	Funder                           *Funder `json:"funder"`
	Pool                             *DPool  `json:"pool"`
	TotalDeficitFunded               *string `json:"totalDeficitFunded"`
	TotalHistoricalDeficitFunded     *string `json:"totalHistoricalDeficitFunded"`
	TotalInterestEarned              *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned    *string `json:"totalHistoricalInterestEarned"`
	TotalRecordedFundedDepositAmount *string `json:"totalRecordedFundedDepositAmount"`
}

type FunderTotalInterestInput struct {
	ID                               *string      `json:"id"`
	Funder                           *FunderInput `json:"funder"`
	Pool                             *DPoolInput  `json:"pool"`
	TotalDeficitFunded               *string      `json:"totalDeficitFunded"`
	TotalHistoricalDeficitFunded     *string      `json:"totalHistoricalDeficitFunded"`
	TotalInterestEarned              *string      `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned    *string      `json:"totalHistoricalInterestEarned"`
	TotalRecordedFundedDepositAmount *string      `json:"totalRecordedFundedDepositAmount"`
}

type Funding struct {
	ID                             *string `json:"id"`
	NftID                          *string `json:"nftID"`
	Funder                         *Funder `json:"funder"`
	Pool                           *DPool  `json:"pool"`
	FromDepositID                  *string `json:"fromDepositID"`
	ToDepositID                    *string `json:"toDepositID"`
	Active                         *bool   `json:"active"`
	RecordedFundedDepositAmount    *string `json:"recordedFundedDepositAmount"`
	RecordedMoneyMarketIncomeIndex *string `json:"recordedMoneyMarketIncomeIndex"`
	InitialFundedDepositAmount     *string `json:"initialFundedDepositAmount"`
	FundedDeficitAmount            *string `json:"fundedDeficitAmount"`
	TotalInterestEarned            *string `json:"totalInterestEarned"`
	MintMPHAmount                  *string `json:"mintMPHAmount"`
}

type FundingInput struct {
	ID                             *string      `json:"id"`
	NftID                          *string      `json:"nftID"`
	Funder                         *FunderInput `json:"funder"`
	Pool                           *DPoolInput  `json:"pool"`
	FromDepositID                  *string      `json:"fromDepositID"`
	ToDepositID                    *string      `json:"toDepositID"`
	Active                         *bool        `json:"active"`
	RecordedFundedDepositAmount    *string      `json:"recordedFundedDepositAmount"`
	RecordedMoneyMarketIncomeIndex *string      `json:"recordedMoneyMarketIncomeIndex"`
	InitialFundedDepositAmount     *string      `json:"initialFundedDepositAmount"`
	FundedDeficitAmount            *string      `json:"fundedDeficitAmount"`
	TotalInterestEarned            *string      `json:"totalInterestEarned"`
	MintMPHAmount                  *string      `json:"mintMPHAmount"`
}

type Mph struct {
	ID                    *string `json:"id"`
	TotalSupply           *string `json:"totalSupply"`
	TotalStakedMPHBalance *string `json:"totalStakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	RewardPerSecond       *string `json:"rewardPerSecond"`
	RewardPerMPHPerSecond *string `json:"rewardPerMPHPerSecond"`
}

type MPHHolder struct {
	ID                    *string `json:"id"`
	Address               *string `json:"address"`
	MphBalance            *string `json:"mphBalance"`
	StakedMPHBalance      *string `json:"stakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
}

type MPHHolderInput struct {
	ID                    *string `json:"id"`
	Address               *string `json:"address"`
	MphBalance            *string `json:"mphBalance"`
	StakedMPHBalance      *string `json:"stakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
}

type MPHInput struct {
	ID                    *string `json:"id"`
	TotalSupply           *string `json:"totalSupply"`
	TotalStakedMPHBalance *string `json:"totalStakedMPHBalance"`
	TotalHistoricalReward *string `json:"totalHistoricalReward"`
	RewardPerSecond       *string `json:"rewardPerSecond"`
	RewardPerMPHPerSecond *string `json:"rewardPerMPHPerSecond"`
}

type User struct {
	ID                 *string             `json:"id"`
	Address            *string             `json:"address"`
	Pools              []*DPool            `json:"pools"`
	NumPools           *string             `json:"numPools"`
	Deposits           []*Deposit          `json:"deposits"`
	NumDeposits        *string             `json:"numDeposits"`
	NumActiveDeposits  *string             `json:"numActiveDeposits"`
	TotalDepositByPool []*UserTotalDeposit `json:"totalDepositByPool"`
	TotalMPHEarned     *string             `json:"totalMPHEarned"`
	TotalMPHPaidBack   *string             `json:"totalMPHPaidBack"`
}

type UserInput struct {
	ID                 *string                  `json:"id"`
	Address            *string                  `json:"address"`
	Pools              []*DPoolInput            `json:"pools"`
	NumPools           *string                  `json:"numPools"`
	Deposits           []*DepositInput          `json:"deposits"`
	NumDeposits        *string                  `json:"numDeposits"`
	NumActiveDeposits  *string                  `json:"numActiveDeposits"`
	TotalDepositByPool []*UserTotalDepositInput `json:"totalDepositByPool"`
	TotalMPHEarned     *string                  `json:"totalMPHEarned"`
	TotalMPHPaidBack   *string                  `json:"totalMPHPaidBack"`
}

type UserTotalDeposit struct {
	ID                            *string `json:"id"`
	User                          *User   `json:"user"`
	Pool                          *DPool  `json:"pool"`
	TotalActiveDeposit            *string `json:"totalActiveDeposit"`
	TotalHistoricalDeposit        *string `json:"totalHistoricalDeposit"`
	TotalInterestEarned           *string `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned *string `json:"totalHistoricalInterestEarned"`
}

type UserTotalDepositInput struct {
	ID                            *string     `json:"id"`
	User                          *UserInput  `json:"user"`
	Pool                          *DPoolInput `json:"pool"`
	TotalActiveDeposit            *string     `json:"totalActiveDeposit"`
	TotalHistoricalDeposit        *string     `json:"totalHistoricalDeposit"`
	TotalInterestEarned           *string     `json:"totalInterestEarned"`
	TotalHistoricalInterestEarned *string     `json:"totalHistoricalInterestEarned"`
}
